import { useState } from 'react';
import { Link, Navigate, useNavigate } from 'react-router-dom';
import { ArrowRight, BookOpen, LockKeyhole, Mail } from 'lucide-react';
import { useAuth } from '../context/AuthContext';

function LoginModern() {
  const { user, loginUser } = useAuth(); const navigate = useNavigate(); const [formData, setFormData] = useState({ email: '', password: '' }); const [error, setError] = useState(''); const [submitting, setSubmitting] = useState(false);
  if (user) return <Navigate to="/" replace />;
  const submit = async (event) => { event.preventDefault(); setSubmitting(true); setError(''); try { await loginUser(formData); navigate('/'); } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to log in. Please try again.'); } finally { setSubmitting(false); } };
  const field = 'mt-2 w-full rounded-xl border border-deep-teal/10 bg-warm-cream/40 px-4 py-3 text-sm outline-none focus:border-deep-teal/40 focus:bg-white focus:ring-4 focus:ring-sage/20';
  return <div className="grid min-h-[calc(100vh-9rem)] place-items-center py-6"><div className="w-full max-w-md rounded-3xl border border-deep-teal/10 bg-white p-6 shadow-xl shadow-deep-teal/10 sm:p-9"><div className="text-center"><span className="mx-auto flex h-12 w-12 items-center justify-center rounded-2xl bg-deep-teal text-muted-gold"><BookOpen size={23} /></span><h1 className="mt-5 font-display text-3xl font-semibold text-deep-teal">Welcome back</h1><p className="mt-2 text-sm text-muted-slate">Continue organizing your study resources.</p></div>{error && <p className="mt-6 rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700" role="alert">{error}</p>}<form onSubmit={submit} className="mt-7 space-y-5"><label className="block text-sm font-semibold text-deep-teal">Email address<div className="relative"><Mail size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-slate" /><input className={`${field} pl-10`} type="email" required value={formData.email} onChange={(event) => setFormData({ ...formData, email: event.target.value })} placeholder="you@example.com" /></div></label><label className="block text-sm font-semibold text-deep-teal">Password<div className="relative"><LockKeyhole size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-slate" /><input className={`${field} pl-10`} type="password" required value={formData.password} onChange={(event) => setFormData({ ...formData, password: event.target.value })} placeholder="Your password" /></div></label><button disabled={submitting} className="flex w-full items-center justify-center gap-2 rounded-lg bg-muted-gold px-4 py-3 text-sm font-semibold text-deep-teal transition hover:bg-gold-hover hover:text-white disabled:opacity-60">{submitting ? 'Logging in...' : 'Login'} {!submitting && <ArrowRight size={16} />}</button></form><p className="mt-7 text-center text-sm text-muted-slate">New to StudyVault? <Link to="/signup" className="font-semibold text-deep-teal hover:text-gold-hover">Create an account</Link></p></div></div>;
}
export default LoginModern;
