import { useState } from 'react';
import { Link, Navigate, useNavigate } from 'react-router-dom';
import { ArrowRight, BookOpen, LockKeyhole, Mail, UserRound } from 'lucide-react';
import { useAuth } from '../context/AuthContext';

function SignupModern() {
  const { user, signupUser } = useAuth(); const navigate = useNavigate(); const [formData, setFormData] = useState({ name: '', email: '', password: '', confirmPassword: '' }); const [error, setError] = useState(''); const [submitting, setSubmitting] = useState(false);
  if (user) return <Navigate to="/" replace />;
  const submit = async (event) => { event.preventDefault(); if (formData.password !== formData.confirmPassword) return setError('Passwords do not match.'); setSubmitting(true); setError(''); try { await signupUser(formData); navigate('/'); } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to create your account. Please try again.'); } finally { setSubmitting(false); } };
  const field = 'mt-2 w-full rounded-xl border border-deep-teal/10 bg-warm-cream/40 px-4 py-3 text-sm outline-none focus:border-deep-teal/40 focus:bg-white focus:ring-4 focus:ring-sage/20';
  return <div className="grid min-h-[calc(100vh-9rem)] place-items-center py-6"><div className="w-full max-w-md rounded-3xl border border-deep-teal/10 bg-white p-6 shadow-xl shadow-deep-teal/10 sm:p-9"><div className="text-center"><span className="mx-auto flex h-12 w-12 items-center justify-center rounded-2xl bg-deep-teal text-muted-gold"><BookOpen size={23} /></span><h1 className="mt-5 font-display text-3xl font-semibold text-deep-teal">Build your study vault</h1><p className="mt-2 text-sm text-muted-slate">A calmer place for everything you are learning.</p></div>{error && <p className="mt-6 rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700" role="alert">{error}</p>}<form onSubmit={submit} className="mt-7 space-y-4"><label className="block text-sm font-semibold text-deep-teal">Full name<div className="relative"><UserRound size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-slate" /><input className={`${field} pl-10`} required value={formData.name} onChange={(event) => setFormData({ ...formData, name: event.target.value })} placeholder="Your name" /></div></label><label className="block text-sm font-semibold text-deep-teal">Email address<div className="relative"><Mail size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-slate" /><input className={`${field} pl-10`} type="email" required value={formData.email} onChange={(event) => setFormData({ ...formData, email: event.target.value })} placeholder="you@example.com" /></div></label><label className="block text-sm font-semibold text-deep-teal">Password<input className={field} type="password" minLength="6" required value={formData.password} onChange={(event) => setFormData({ ...formData, password: event.target.value })} placeholder="At least 6 characters" /></label><label className="block text-sm font-semibold text-deep-teal">Confirm password<div className="relative"><LockKeyhole size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-slate" /><input className={`${field} pl-10`} type="password" required value={formData.confirmPassword} onChange={(event) => setFormData({ ...formData, confirmPassword: event.target.value })} placeholder="Repeat your password" /></div></label><button disabled={submitting} className="mt-2 flex w-full items-center justify-center gap-2 rounded-lg bg-muted-gold px-4 py-3 text-sm font-semibold text-deep-teal transition hover:bg-gold-hover hover:text-white disabled:opacity-60">{submitting ? 'Creating account...' : 'Create account'} {!submitting && <ArrowRight size={16} />}</button></form><p className="mt-7 text-center text-sm text-muted-slate">Already have an account? <Link to="/login" className="font-semibold text-deep-teal hover:text-gold-hover">Login</Link></p></div></div>;
}
export default SignupModern;
